package Commands.Enums;

import Commands.CreateNewBug;

public enum CommandType {
    CREATENEWPERSON,
    CREATENEWBUG,
    CREATENEWSTORY,
    CREATENEWFEEDBACK,
    CREATENEWTEAM,
    ADDPERSONTOTEAM,
    ASSIGNATASKTOAPERSON,
    CREATENEWBOARDINATEAM,
    SHOWALLPEOPLE,
    SHOWWALLTEAMBOARDS,
    SHOWALLTEAMS,
    SHOWALLTHETEAMMEMBERS,
    SHOWBOARDSACTIVITY,
    SHOWPERSONACTIVITY,
    SHOWTEAMSACTIVITY,
    LISTALLBUGS,
    LISTALLFEEDBACKS,
    LISTALLSTORIES,
    LISTALLTASKS,
    LISTALLTASKSWITHASSIGNEE,
    ADDSTEPSTOBUG
}
